In [1]:
import pandas as pd

df = pd.read_csv("../data/weersdata.csv")

In [2]:
df.head()

        datum  temperatuur  neerslag_mm  windsnelheid     stad
0  2024-01-01          3.2          1.4           4.2  De Bilt
1  2024-01-02          4.1          0.0           3.1  De Bilt
2  2024-01-03          2.8          3.2           5.6  De Bilt
3  2024-01-04          1.5          0.5           2.3  De Bilt
4  2024-01-05          5.0          0.0           4.8  De Bilt

In [6]:
df.shape

(15, 5)

In [12]:
df.describe()

       temperatuur  neerslag_mm  windsnelheid
count    15.000000    15.000000     15.000000
mean      3.693333     1.366667      4.613333
std       1.788242     1.541644      1.446111
min       0.500000     0.000000      2.300000
25%       2.500000     0.000000      3.550000
50%       3.700000     1.100000      4.400000
75%       4.900000     2.450000      5.550000
max       6.800000     4.500000      7.200000

In [11]:
df.dtypes

datum               str
temperatuur     float64
neerslag_mm     float64
windsnelheid    float64
stad                str
dtype: object

In [13]:
gemiddeld = df["windsnelheid"].mean()
print(f"Gemiddelde windsnelheid: {gemiddeld:.1f} km/h")

Gemiddelde windsnelheid: 4.6 km/h

In [15]:
koude_dagen = df[df["temperatuur"] < 3]
print("Koude dagen:")
print(koude_dagen)

Koude dagen:
         datum  temperatuur  neerslag_mm  windsnelheid     stad
2   2024-01-03          2.8          3.2           5.6  De Bilt
3   2024-01-04          1.5          0.5           2.3  De Bilt
8   2024-01-09          2.2          1.2           5.5  De Bilt
9   2024-01-10          1.8          0.0           4.1  De Bilt
10  2024-01-11          0.5          2.8           6.8  De Bilt

In [17]:
natte_dagen = df[df["neerslag_mm"] > 2]
print("Natte dagen:")
print(natte_dagen)

Natte dagen:
         datum  temperatuur  neerslag_mm  windsnelheid     stad
2   2024-01-03          2.8          3.2           5.6  De Bilt
5   2024-01-06          6.2          2.1           6.1  De Bilt
7   2024-01-08          3.1          4.5           7.2  De Bilt
10  2024-01-11          0.5          2.8           6.8  De Bilt
14  2024-01-15          4.2          3.7           5.1  De Bilt